### ISSUE TITLE
Necessary extensions are hidden in Resources folder

### ISSUE THREAD

**Issue by Gargo** [Mijick/GridView-Demo#2]
Man, Resources folder is usually used for images, data, json and etc., not source code. It is really confusing when you want to import minimal working project (4 files) into your own one but it suddenly happens that there are much more sources

**Comment by FulcrumOne** [comment]
Man, this is a demo project that wasn't intended to be merged with any existing project - it's only to demonstrate how you can use the library. 
Thank you however for your priceless hints of how I can better organise the file system in my projects, but I think I'll stick with my system. 

Have a good day,
T.K.
